"""
Professional Self-Care Exercise Library
45 evidence-based exercises: 15 breathing, 15 mindfulness, 15 meditation
"""

# Import for filtering
from typing import List, Dict, Any

BREATHING_EXERCISES = [
    {"id": "breath_1", "title": "4-7-8 Breathing", "duration_minutes": 5, "difficulty": "easy", "description": "This powerful technique was developed by Dr. Andrew Weil and acts as a natural tranquilizer for the nervous system. The extended exhale activates your parasympathetic nervous system, signaling your body to relax and prepare for rest. Regular practice can help you fall asleep faster and manage anxiety in stressful moments.", "instructions": "Sit comfortably with your back straight. Exhale completely through your mouth. Close your mouth and inhale quietly through your nose for 4 counts. Hold your breath for 7 counts. Exhale completely through your mouth for 8 counts, making a whoosh sound. Repeat this cycle 4 times.", "benefits": "Reduces anxiety, promotes sleep, lowers blood pressure, calms racing thoughts"},
    {"id": "breath_2", "title": "Box Breathing", "duration_minutes": 5, "difficulty": "easy", "description": "Also known as square breathing, this technique is used by Navy SEALs to stay calm and focused in high-pressure situations. The equal counts create a balanced rhythm that helps regulate your autonomic nervous system. This practice enhances mental clarity and emotional control while reducing stress hormones.", "instructions": "Sit upright in a quiet space. Exhale all the air from your lungs. Inhale slowly through your nose for 4 counts. Hold your breath for 4 counts. Exhale through your mouth for 4 counts. Hold empty for 4 counts. Repeat for 5 minutes.", "benefits": "Enhances focus, reduces stress, improves performance under pressure, increases mental clarity"},
    {"id": "breath_3", "title": "Diaphragmatic Breathing", "duration_minutes": 10, "difficulty": "easy", "description": "This foundational breathing technique engages your diaphragm fully, allowing your lungs to expand completely and maximize oxygen intake. By breathing into your belly rather than your chest, you activate the vagus nerve which triggers your body's relaxation response. This is one of the most effective ways to reduce cortisol and calm your nervous system.", "instructions": "Lie down or sit comfortably. Place one hand on your chest and one on your belly. Breathe in slowly through your nose, allowing your belly to rise while your chest remains relatively still. Exhale slowly through pursed lips, feeling your belly fall. Continue for 10 minutes, maintaining a slow, steady rhythm.", "benefits": "Lowers heart rate, reduces cortisol levels, improves oxygen efficiency, strengthens diaphragm"},
    {"id": "breath_4", "title": "Alternate Nostril Breathing", "duration_minutes": 10, "difficulty": "moderate", "description": "Balances left and right brain hemispheres.", "instructions": "Close right nostril, inhale left. Close left, exhale right. Repeat alternating for 10 minutes.", "benefits": "Balances nervous system, improves focus, reduces anxiety"},
    {"id": "breath_5", "title": "Resonant Breathing", "duration_minutes": 10, "difficulty": "easy", "description": "5-6 breaths per minute for optimal heart rate variability.", "instructions": "Breathe in for 5 seconds, out for 5 seconds. Maintain smooth rhythm for 10 minutes.", "benefits": "Maximizes HRV, reduces stress, improves emotional regulation"},
    {"id": "breath_6", "title": "Pursed Lip Breathing", "duration_minutes": 5, "difficulty": "easy", "description": "Slows breathing rate and keeps airways open longer.", "instructions": "Inhale through nose for 2 counts. Purse lips, exhale for 4 counts. Repeat 5 minutes.", "benefits": "Improves lung function, reduces shortness of breath"},
    {"id": "breath_7", "title": "Lion's Breath", "duration_minutes": 5, "difficulty": "easy", "description": "Energizing breath that releases facial tension.", "instructions": "Inhale deeply. Open mouth wide, stick out tongue, exhale forcefully with 'ha' sound. Repeat 5-7 times.", "benefits": "Releases tension, energizes body, improves confidence"},
    {"id": "breath_8", "title": "Breath Counting", "duration_minutes": 15, "difficulty": "moderate", "description": "Zen technique combining breath awareness with counting.", "instructions": "Count each exhale from 1 to 10. Return to 1 after 10. If you lose count, start over.", "benefits": "Develops concentration, calms mind, builds mindfulness"},
    {"id": "breath_9", "title": "Coherent Breathing", "duration_minutes": 20, "difficulty": "moderate", "description": "5 breaths per minute for maximum coherence.", "instructions": "Inhale for 6 seconds, exhale for 6 seconds. Maintain for 20 minutes.", "benefits": "Optimizes autonomic function, reduces stress hormones"},
    {"id": "breath_10", "title": "Bellows Breath", "duration_minutes": 5, "difficulty": "challenging", "description": "Rapid, forceful breathing to energize and clear mind.", "instructions": "Rapid forceful breathing through nose for 10 breaths. Deep breath, hold. Repeat 3 rounds.", "benefits": "Increases energy, clears sinuses, improves focus"},
    {"id": "breath_11", "title": "Humming Bee Breath", "duration_minutes": 10, "difficulty": "easy", "description": "Calming breath with humming vibration.", "instructions": "Close ears with fingers. Inhale deeply. Exhale while humming. Feel vibration. Repeat 10 times.", "benefits": "Reduces anger and anxiety, lowers blood pressure"},
    {"id": "breath_12", "title": "Three-Part Breath", "duration_minutes": 10, "difficulty": "moderate", "description": "Complete yogic breath filling belly, ribs, chest.", "instructions": "Inhale into belly first, then ribs, then chest. Exhale from chest, ribs, belly. Repeat 10 minutes.", "benefits": "Increases lung capacity, deeply relaxing"},
    {"id": "breath_13", "title": "Cooling Breath", "duration_minutes": 5, "difficulty": "easy", "description": "Reduces body temperature and calms mind.", "instructions": "Curl tongue into tube. Inhale through tongue. Close mouth, exhale through nose. Repeat 10-15 times.", "benefits": "Cools body, reduces anger, calms nervous system"},
    {"id": "breath_14", "title": "Equal Breathing", "duration_minutes": 15, "difficulty": "easy", "description": "Equal length inhales and exhales for balance.", "instructions": "Breathe in for 4 counts, out for 4 counts. Gradually increase to 6-8 counts. Continue 15 minutes.", "benefits": "Balances nervous system, improves focus"},
    {"id": "breath_15", "title": "Skull Shining Breath", "duration_minutes": 10, "difficulty": "challenging", "description": "Rapid exhalations to energize and cleanse.", "instructions": "Forceful exhales by contracting abdomen. Passive inhales. 20 rapid breaths. Rest. 3 rounds.", "benefits": "Energizes body, clears respiratory system"}
]

MINDFULNESS_EXERCISES = [
    {"id": "mind_1", "title": "Body Scan", "duration_minutes": 15, "difficulty": "easy", "description": "Systematic attention to physical sensations throughout body.", "instructions": "Lie down. Focus on toes, slowly move attention up through entire body to crown of head.", "benefits": "Reduces tension, improves body awareness, promotes relaxation"},
    {"id": "mind_2", "title": "Mindful Walking", "duration_minutes": 10, "difficulty": "easy", "description": "Walking meditation with full attention to movement.", "instructions": "Walk slowly. Notice lifting, moving, placing of each foot. Maintain present awareness.", "benefits": "Grounds awareness, combines movement with mindfulness"},
    {"id": "mind_3", "title": "Five Senses Exercise", "duration_minutes": 5, "difficulty": "easy", "description": "Ground yourself by engaging all five senses.", "instructions": "Notice 5 things you see, 4 you touch, 3 you hear, 2 you smell, 1 you taste.", "benefits": "Rapid grounding, reduces anxiety, brings awareness to present"},
    {"id": "mind_4", "title": "Mindful Eating", "duration_minutes": 15, "difficulty": "easy", "description": "Eat one item with complete attention.", "instructions": "Choose small food. Observe visually, smell, feel texture. Place in mouth, notice taste. Chew slowly.", "benefits": "Improves relationship with food, enhances enjoyment"},
    {"id": "mind_5", "title": "Loving-Kindness Practice", "duration_minutes": 10, "difficulty": "moderate", "description": "Cultivate compassion for self and others.", "instructions": "Say 'May I be happy, healthy, safe, at ease.' Repeat for loved one, neutral person, difficult person.", "benefits": "Increases compassion, reduces self-criticism"},
    {"id": "mind_6", "title": "RAIN Technique", "duration_minutes": 10, "difficulty": "moderate", "description": "Recognize, Allow, Investigate, Nurture difficult emotions.", "instructions": "Recognize feeling. Allow it. Investigate with kindness. Nurture with self-compassion.", "benefits": "Processes difficult emotions, builds emotional intelligence"},
    {"id": "mind_7", "title": "Mindful Listening", "duration_minutes": 10, "difficulty": "easy", "description": "Listen to sounds without judgment.", "instructions": "Close eyes. Notice sounds near and far. Don't label. Notice silence between sounds.", "benefits": "Develops concentration, reduces mental chatter"},
    {"id": "mind_8", "title": "Thought Labeling", "duration_minutes": 15, "difficulty": "moderate", "description": "Observe thoughts as mental events, not facts.", "instructions": "Notice thoughts. Label them: 'thinking', 'planning', 'worrying'. Let them pass like clouds.", "benefits": "Creates distance from thoughts, reduces rumination"},
    {"id": "mind_9", "title": "Gratitude Reflection", "duration_minutes": 10, "difficulty": "easy", "description": "Mindfully reflect on things you're grateful for.", "instructions": "Think of 3 things you're grateful for. Really feel the gratitude. Notice sensations in body.", "benefits": "Increases positive emotions, improves mood"},
    {"id": "mind_10", "title": "Mountain Meditation", "duration_minutes": 15, "difficulty": "moderate", "description": "Embody stability and strength of a mountain.", "instructions": "Sit with dignified posture. Visualize yourself as mountain. Weather passes, mountain remains unchanged.", "benefits": "Builds inner stability, develops equanimity"},
    {"id": "mind_11", "title": "Mindful Stretching", "duration_minutes": 10, "difficulty": "easy", "description": "Gentle stretches with full awareness.", "instructions": "Slowly stretch arms, neck, shoulders, back. Notice sensations. Breathe into stretch. Honor body's limits.", "benefits": "Releases physical tension, improves body awareness"},
    {"id": "mind_12", "title": "Noting Practice", "duration_minutes": 20, "difficulty": "moderate", "description": "Mental noting of present moment experience.", "instructions": "Notice predominant experience. Mentally note: 'hearing', 'feeling', 'thinking'. Brief notes only.", "benefits": "Develops clear seeing, reduces identification with experience"},
    {"id": "mind_13", "title": "3-Minute Breathing Space", "duration_minutes": 3, "difficulty": "easy", "description": "Quick centering practice.", "instructions": "Min 1: Acknowledge present. Min 2: Focus on breath. Min 3: Expand awareness to body and surroundings.", "benefits": "Quick reset, accessible anywhere, reduces stress rapidly"},
    {"id": "mind_14", "title": "Choiceless Awareness", "duration_minutes": 20, "difficulty": "challenging", "description": "Open monitoring of all experience.", "instructions": "Let awareness be open. Don't focus on anything specific. Notice whatever arises without judgment.", "benefits": "Develops non-reactive awareness, deepens insight"},
    {"id": "mind_15", "title": "Mindful Hand Washing", "duration_minutes": 5, "difficulty": "easy", "description": "Transform routine into mindfulness practice.", "instructions": "Feel water temperature, smell soap, notice lather texture, feel rinsing, dry with full attention.", "benefits": "Brings mindfulness to daily life, builds habit"}
]

MEDITATION_EXERCISES = [
    {"id": "med_1", "title": "Breath Awareness Meditation", "duration_minutes": 10, "difficulty": "easy", "description": "Foundation practice focusing on natural breath.", "instructions": "Sit comfortably. Breathe naturally. Notice breath at nostrils or belly. When mind wanders, gently return.", "benefits": "Develops concentration, calms mind, foundation for all meditation"},
    {"id": "med_2", "title": "Mantra Meditation", "duration_minutes": 20, "difficulty": "easy", "description": "Repeat sacred word to focus mind.", "instructions": "Choose mantra (Om, Peace, So Hum). Repeat silently. When mind wanders, return to mantra.", "benefits": "Quiets mental chatter, induces relaxation response"},
    {"id": "med_3", "title": "Visualization Meditation", "duration_minutes": 15, "difficulty": "moderate", "description": "Create peaceful mental imagery.", "instructions": "Visualize peaceful place. Engage all senses. Notice colors, sounds, smells. Feel peace and safety.", "benefits": "Reduces stress, improves mood, enhances creativity"},
    {"id": "med_4", "title": "Zen Meditation (Zazen)", "duration_minutes": 25, "difficulty": "challenging", "description": "Sitting meditation with focus on posture.", "instructions": "Sit on cushion, legs crossed. Eyes half-open. Breathe naturally. Count breaths or just sit.", "benefits": "Develops discipline, deepens awareness, cultivates presence"},
    {"id": "med_5", "title": "Progressive Muscle Relaxation", "duration_minutes": 20, "difficulty": "easy", "description": "Systematically tense and release muscles.", "instructions": "Lie down. Tense feet for 5 seconds, release. Move up through all muscle groups to face.", "benefits": "Releases physical tension, reduces anxiety, improves sleep"},
    {"id": "med_6", "title": "Open Awareness Meditation", "duration_minutes": 20, "difficulty": "challenging", "description": "Rest in spacious awareness without object.", "instructions": "Sit comfortably. Let go of all techniques. Rest in natural awareness. Don't focus on anything.", "benefits": "Deepest form of meditation, cultivates non-dual awareness"},
    {"id": "med_7", "title": "Chakra Meditation", "duration_minutes": 30, "difficulty": "moderate", "description": "Focus on energy centers along spine.", "instructions": "Start at root chakra (red). Move up through all 7 chakras. Spend 3-5 minutes on each.", "benefits": "Balances energy, promotes spiritual growth, holistic wellness"},
    {"id": "med_8", "title": "Sound Bath Meditation", "duration_minutes": 20, "difficulty": "easy", "description": "Meditate with singing bowls or healing sounds.", "instructions": "Lie down. Play singing bowl or healing music. Let sound wash over you. Feel vibrations in body.", "benefits": "Deep relaxation, reduces stress, balances nervous system"},
    {"id": "med_9", "title": "Candle Gazing", "duration_minutes": 15, "difficulty": "moderate", "description": "Focus on candle flame to develop concentration.", "instructions": "Gaze at flame without blinking. When eyes water, close and visualize flame at third eye. Repeat.", "benefits": "Improves concentration, cleanses eyes, develops focus"},
    {"id": "med_10", "title": "Walking Meditation", "duration_minutes": 20, "difficulty": "easy", "description": "Formal walking practice with slow steps.", "instructions": "Walk very slowly. Notice lifting, moving, placing of each foot. Turn mindfully. Continue 20 minutes.", "benefits": "Combines movement with meditation, develops mindfulness"},
    {"id": "med_11", "title": "Yoga Nidra", "duration_minutes": 30, "difficulty": "easy", "description": "Yogic sleep - deep relaxation while aware.", "instructions": "Lie down. Set intention. Rotate awareness through body. Breathe awareness. Visualizations.", "benefits": "Profound relaxation, reduces insomnia, restores nervous system"},
    {"id": "med_12", "title": "Mindfulness of Emotions", "duration_minutes": 15, "difficulty": "moderate", "description": "Observe emotions without attachment.", "instructions": "Notice current emotional state. Where in body? What quality? Observe without judgment. Let it be.", "benefits": "Emotional regulation, reduces reactivity, builds emotional intelligence"},
    {"id": "med_13", "title": "Transcendental Meditation", "duration_minutes": 20, "difficulty": "easy", "description": "Effortless technique using mantra.", "instructions": "Think your mantra effortlessly. Don't concentrate. Let mantra come naturally. Practice twice daily.", "benefits": "Reduces stress, lowers blood pressure, improves cardiovascular health"},
    {"id": "med_14", "title": "Metta Meditation (Extended)", "duration_minutes": 30, "difficulty": "moderate", "description": "Extended loving-kindness for all beings.", "instructions": "Start with self. Extend to loved ones, neutral people, difficult people, all beings. Feel universal love.", "benefits": "Increases compassion, reduces negative emotions, improves relationships"},
    {"id": "med_15", "title": "Silent Sitting", "duration_minutes": 45, "difficulty": "challenging", "description": "Extended silent meditation without technique.", "instructions": "Sit in stable posture. No technique, just sit. Be with whatever arises. Don't move unless necessary.", "benefits": "Develops deep concentration, builds resilience, profound insight"}
]

def get_exercises_by_time(category: str, available_minutes: int, max_results: int = 5) -> List[Dict[str, Any]]:
    """Get exercises filtered by available time"""
    if category == "breathing":
        exercises = BREATHING_EXERCISES
    elif category == "mindfulness":
        exercises = MINDFULNESS_EXERCISES
    elif category == "meditation":
        exercises = MEDITATION_EXERCISES
    else:
        return []
    
    # Filter by time (exercises that fit within available time)
    filtered = [ex for ex in exercises if ex["duration_minutes"] <= available_minutes]
    
    # Sort by duration (closest to available time first)
    filtered.sort(key=lambda x: abs(x["duration_minutes"] - available_minutes))
    
    return filtered[:max_results]
