"""
Professional Self-Care Exercise Library
45 evidence-based exercises: 15 breathing, 15 mindfulness, 15 meditation
"""

# Import for filtering
from typing import List, Dict, Any

BREATHING_EXERCISES = [
    {"id": "breath_1", "title": "4-7-8 Breathing", "duration_minutes": 5, "difficulty": "easy", "description": "This powerful technique was developed by Dr. Andrew Weil and acts as a natural tranquilizer for the nervous system. The extended exhale activates your parasympathetic nervous system, signaling your body to relax and prepare for rest. Regular practice can help you fall asleep faster and manage anxiety in stressful moments.", "instructions": "Sit comfortably with your back straight. Exhale completely through your mouth. Close your mouth and inhale quietly through your nose for 4 counts. Hold your breath for 7 counts. Exhale completely through your mouth for 8 counts, making a whoosh sound. Repeat this cycle 4 times.", "benefits": "Reduces anxiety, promotes sleep, lowers blood pressure, calms racing thoughts"},
    {"id": "breath_2", "title": "Box Breathing", "duration_minutes": 5, "difficulty": "easy", "description": "Also known as square breathing, this technique is used by Navy SEALs to stay calm and focused in high-pressure situations. The equal counts create a balanced rhythm that helps regulate your autonomic nervous system. This practice enhances mental clarity and emotional control while reducing stress hormones.", "instructions": "Sit upright in a quiet space. Exhale all the air from your lungs. Inhale slowly through your nose for 4 counts. Hold your breath for 4 counts. Exhale through your mouth for 4 counts. Hold empty for 4 counts. Repeat for 5 minutes.", "benefits": "Enhances focus, reduces stress, improves performance under pressure, increases mental clarity"},
    {"id": "breath_3", "title": "Diaphragmatic Breathing", "duration_minutes": 10, "difficulty": "easy", "description": "This foundational breathing technique engages your diaphragm fully, allowing your lungs to expand completely and maximize oxygen intake. By breathing into your belly rather than your chest, you activate the vagus nerve which triggers your body's relaxation response. This is one of the most effective ways to reduce cortisol and calm your nervous system.", "instructions": "Lie down or sit comfortably. Place one hand on your chest and one on your belly. Breathe in slowly through your nose, allowing your belly to rise while your chest remains relatively still. Exhale slowly through pursed lips, feeling your belly fall. Continue for 10 minutes, maintaining a slow, steady rhythm.", "benefits": "Lowers heart rate, reduces cortisol levels, improves oxygen efficiency, strengthens diaphragm"},
    {"id": "breath_4", "title": "Alternate Nostril Breathing", "duration_minutes": 10, "difficulty": "moderate", "description": "This ancient yogic practice balances the left and right hemispheres of your brain, promoting mental clarity and emotional equilibrium. By alternating nostrils, you harmonize the flow of energy through your body's subtle channels. This technique is particularly effective for reducing anxiety and improving concentration before important tasks.", "instructions": "Sit comfortably with your spine straight. Use your right thumb to close your right nostril and inhale slowly through your left nostril. Close your left nostril with your ring finger, release your thumb, and exhale through your right nostril. Inhale through the right, then switch and exhale through the left. Continue alternating for 10 minutes.", "benefits": "Balances nervous system, improves focus, reduces anxiety, harmonizes brain hemispheres"},
    {"id": "breath_5", "title": "Resonant Breathing", "duration_minutes": 10, "difficulty": "easy", "description": "Breathing at approximately 5-6 breaths per minute creates a state of resonance in your cardiovascular system, maximizing heart rate variability. This optimal breathing rate synchronizes your heart, lungs, and brain, creating coherence throughout your body. Research shows this is one of the most effective breathing patterns for reducing stress and improving emotional regulation.", "instructions": "Sit or lie comfortably. Inhale smoothly through your nose for 5 seconds. Exhale smoothly through your nose for 5 seconds. Maintain this steady, even rhythm without pauses between breaths. Focus on making each breath smooth and effortless. Continue for 10 minutes.", "benefits": "Maximizes heart rate variability, reduces stress hormones, improves emotional regulation, enhances cardiovascular health"},
    {"id": "breath_6", "title": "Pursed Lip Breathing", "duration_minutes": 5, "difficulty": "easy", "description": "This simple yet powerful technique slows your breathing rate and keeps your airways open longer, making each breath more efficient. By creating back-pressure in your airways, you prevent them from collapsing and improve oxygen exchange. This is especially helpful for people with respiratory conditions or anyone experiencing shortness of breath or anxiety.", "instructions": "Relax your neck and shoulders. Breathe in slowly through your nose for 2 counts. Purse your lips as if you're about to whistle or blow out a candle. Breathe out slowly and gently through your pursed lips for 4 counts. Don't force the exhale. Repeat for 5 minutes.", "benefits": "Improves lung function, reduces shortness of breath, calms anxiety, increases oxygen efficiency"},
    {"id": "breath_7", "title": "Lion's Breath", "duration_minutes": 5, "difficulty": "easy", "description": "This playful and energizing breath releases tension stored in your face, jaw, and throat while boosting confidence and vitality. The forceful exhale helps expel stale air and negative energy, leaving you feeling refreshed and empowered. It's particularly effective when you're feeling frustrated, anxious, or need a quick energy boost.", "instructions": "Kneel or sit comfortably. Inhale deeply through your nose. Open your mouth wide, stick out your tongue toward your chin, and exhale forcefully with a loud 'ha' sound. Gaze upward or at your third eye. Feel the release in your face and throat. Repeat 5-7 times.", "benefits": "Releases facial and jaw tension, energizes body, improves confidence, expels negative energy"},
    {"id": "breath_8", "title": "Breath Counting", "duration_minutes": 15, "difficulty": "moderate", "description": "This classic Zen meditation technique trains your mind to stay present by combining breath awareness with simple counting. When your mind wanders and you lose count, you simply begin again without judgment, building patience and self-compassion. Over time, this practice significantly improves concentration and reduces mental chatter.", "instructions": "Sit in a comfortable meditation posture. Breathe naturally and count '1' on your first exhale. Continue counting each exhale up to 10. After reaching 10, return to 1 and begin again. If you lose count or your mind wanders, gently return to 1 without self-criticism. Practice for 15 minutes.", "benefits": "Develops concentration, calms racing mind, builds mindfulness, cultivates patience"},
    {"id": "breath_9", "title": "Coherent Breathing", "duration_minutes": 20, "difficulty": "moderate", "description": "Breathing at exactly 5 breaths per minute creates maximum coherence between your heart, brain, and respiratory system, optimizing your body's natural healing abilities. This precise rhythm has been scientifically proven to reduce stress hormones, lower blood pressure, and improve overall autonomic nervous system function. Regular practice can transform your stress response and emotional resilience.", "instructions": "Sit comfortably with your spine straight. Set a timer for 20 minutes. Inhale slowly through your nose for 6 seconds. Exhale slowly through your nose for 6 seconds. Maintain this exact rhythm throughout the practice. Keep your breathing smooth, effortless, and consistent. Focus on the steady rhythm.", "benefits": "Optimizes autonomic nervous system, reduces stress hormones, lowers blood pressure, improves heart rate variability"},
    {"id": "breath_10", "title": "Bellows Breath", "duration_minutes": 5, "difficulty": "challenging", "description": "This vigorous pranayama technique rapidly oxygenates your blood and energizes your entire system, clearing mental fog and boosting alertness. The forceful breathing clears your sinuses and respiratory passages while stimulating your nervous system. Use this practice when you need a natural energy boost or mental clarity, but avoid it if you have high blood pressure or are pregnant.", "instructions": "Sit with your spine straight. Take a deep breath in. Begin rapid, forceful breathing through your nose - both inhales and exhales should be strong and equal. Complete 10 rapid breaths. Take a deep inhale, hold briefly, then exhale slowly. Rest for a moment. Repeat for 3 rounds total.", "benefits": "Increases energy and alertness, clears sinuses, improves focus, oxygenates blood"},
    {"id": "breath_11", "title": "Humming Bee Breath", "duration_minutes": 10, "difficulty": "easy", "description": "The gentle humming vibration in this practice creates a soothing internal massage that calms your nervous system and quiets mental chatter. The sound vibrations stimulate your vagus nerve, triggering a deep relaxation response throughout your body. This is particularly effective for reducing anger, frustration, and anxiety while lowering blood pressure.", "instructions": "Sit comfortably and close your eyes. Place your index fingers gently on your ears to close them. Inhale deeply through your nose. As you exhale, make a steady humming sound like a bee. Feel the vibration resonating in your head and chest. Keep your mouth closed throughout. Repeat 10 times, focusing on the calming vibration.", "benefits": "Reduces anger and anxiety, lowers blood pressure, calms nervous system, improves concentration"},
    {"id": "breath_12", "title": "Three-Part Breath", "duration_minutes": 10, "difficulty": "moderate", "description": "This complete yogic breathing technique maximizes your lung capacity by filling all three chambers of your lungs sequentially. By consciously engaging your entire respiratory system, you increase oxygen intake and promote full-body relaxation. This foundational practice teaches you to breathe more efficiently in daily life.", "instructions": "Lie down or sit comfortably. Exhale completely. Inhale slowly, first filling your belly, then expanding your ribcage, finally lifting your upper chest. Exhale in reverse order: release from chest, then ribs, finally belly. Keep the breath smooth and continuous. Repeat for 10 minutes.", "benefits": "Increases lung capacity, deeply relaxing, improves breathing efficiency, oxygenates entire body"},
    {"id": "breath_13", "title": "Cooling Breath", "duration_minutes": 5, "difficulty": "easy", "description": "This refreshing breath literally cools your body temperature while calming heated emotions like anger and frustration. The evaporation of moisture on your tongue creates a cooling sensation that spreads throughout your system. Use this practice on hot days, after exercise, or when you're feeling emotionally overheated.", "instructions": "Sit comfortably. Curl your tongue into a tube (or purse your lips if you can't curl your tongue). Inhale slowly through your curled tongue, feeling the cool air. Close your mouth and exhale slowly through your nose. Feel the cooling sensation spread. Repeat 10-15 times.", "benefits": "Cools body temperature, reduces anger and frustration, calms nervous system, refreshes mind"},
    {"id": "breath_14", "title": "Equal Breathing", "duration_minutes": 15, "difficulty": "easy", "description": "This balanced breathing pattern creates equilibrium in your nervous system by making your inhales and exhales equal in length. The symmetry promotes mental clarity and emotional stability while reducing anxiety. As you practice, you can gradually lengthen the count, deepening the calming effects.", "instructions": "Sit or lie comfortably. Breathe in through your nose for 4 counts. Breathe out through your nose for 4 counts. Keep the rhythm smooth and steady. As you become comfortable, gradually increase to 6, then 8 counts. Maintain equal length inhales and exhales. Continue for 15 minutes.", "benefits": "Balances nervous system, improves focus, reduces anxiety, creates mental clarity"},
    {"id": "breath_15", "title": "Skull Shining Breath", "duration_minutes": 10, "difficulty": "challenging", "description": "This powerful cleansing breath energizes your entire system while clearing your respiratory passages and mind. The rapid, forceful exhales massage your internal organs and stimulate your digestive system. This practice is excellent for morning energy or when you need mental clarity, but should be avoided if pregnant or with high blood pressure.", "instructions": "Sit with your spine straight. Take a deep breath in. Begin rapid, forceful exhales by quickly contracting your abdomen. Let the inhales happen passively. Complete 20 rapid breaths. Take a deep breath in, hold briefly, exhale slowly. Rest for 30 seconds. Repeat for 3 rounds total.", "benefits": "Energizes entire body, clears respiratory system, improves digestion, sharpens mental clarity"}
]

MINDFULNESS_EXERCISES = [
    {"id": "mind_1", "title": "Body Scan", "duration_minutes": 15, "difficulty": "easy", "description": "This foundational mindfulness practice systematically brings awareness to every part of your body, releasing unconscious tension and promoting deep relaxation. By noticing physical sensations without judgment, you develop a stronger mind-body connection and learn to recognize stress signals early. Regular practice can significantly reduce chronic pain and improve sleep quality.", "instructions": "Lie down in a comfortable position. Close your eyes and take a few deep breaths. Begin by focusing attention on your toes, noticing any sensations. Slowly move your awareness up through your feet, ankles, calves, knees, and thighs. Continue through your torso, arms, neck, and head. Spend 1-2 minutes on each body region, simply observing without trying to change anything.", "benefits": "Reduces physical tension, improves body awareness, promotes deep relaxation, reduces chronic pain"},
    {"id": "mind_2", "title": "Mindful Walking", "duration_minutes": 10, "difficulty": "easy", "description": "This moving meditation brings complete awareness to the simple act of walking, grounding you in the present moment through physical sensation. Unlike sitting meditation, this practice is accessible and energizing, making it perfect for those who find stillness challenging. Walking mindfully transforms a routine activity into a powerful stress-reduction tool you can use anywhere.", "instructions": "Find a quiet path where you can walk slowly without interruption. Walk at a natural but deliberate pace. Notice the sensation of lifting your foot, moving it through space, and placing it down. Feel the weight transfer from heel to toe. When your mind wanders, gently bring attention back to the physical sensations of walking. Continue for 10 minutes.", "benefits": "Grounds awareness in present moment, combines movement with mindfulness, reduces anxiety, accessible practice"},
    {"id": "mind_3", "title": "Five Senses Exercise", "duration_minutes": 5, "difficulty": "easy", "description": "This quick grounding technique interrupts anxiety spirals by anchoring your awareness in physical reality through your five senses. By systematically engaging each sense, you shift from worrying about the past or future to experiencing the present moment. This is one of the most effective rapid interventions for panic attacks and overwhelming emotions.", "instructions": "Pause wherever you are and take a deep breath. Notice 5 things you can see (colors, shapes, details). Notice 4 things you can physically touch (textures, temperatures). Notice 3 things you can hear (near and far sounds). Notice 2 things you can smell (or remember smelling). Notice 1 thing you can taste. Take another deep breath.", "benefits": "Rapid grounding technique, interrupts anxiety spirals, brings immediate awareness to present, stops panic attacks"},
    {"id": "mind_4", "title": "Mindful Eating", "duration_minutes": 15, "difficulty": "easy", "description": "This practice transforms eating from an automatic activity into a rich sensory experience, helping you develop a healthier relationship with food. By eating slowly and attentively, you naturally eat less, digest better, and enjoy your food more. This foundational mindfulness exercise reveals how often we eat while distracted and disconnected from our bodies.", "instructions": "Choose a small food item like a raisin or piece of chocolate. Before eating, observe it visually - color, shape, texture. Smell it deeply. Feel its texture in your hand. Place it in your mouth but don't chew yet - notice the taste and texture. Chew slowly, noticing how the taste and texture change. Swallow mindfully. Notice the entire experience.", "benefits": "Improves relationship with food, enhances enjoyment and satisfaction, aids digestion, promotes healthy eating habits"},
    {"id": "mind_5", "title": "Loving-Kindness Practice", "duration_minutes": 10, "difficulty": "moderate", "description": "This heart-opening practice systematically cultivates compassion for yourself and others, starting with self-love and expanding outward. Research shows that regular loving-kindness meditation increases positive emotions, social connection, and overall life satisfaction. By wishing well for difficult people, you free yourself from the burden of resentment and anger.", "instructions": "Sit comfortably and close your eyes. Place a hand on your heart. Silently repeat: 'May I be happy. May I be healthy. May I be safe. May I live with ease.' Feel the warmth of these wishes. Next, bring to mind a loved one and repeat the phrases for them. Then a neutral person. Finally, if ready, a difficult person. End by extending wishes to all beings.", "benefits": "Increases compassion and self-love, reduces self-criticism, improves relationships, decreases resentment"},
    {"id": "mind_6", "title": "RAIN Technique", "duration_minutes": 10, "difficulty": "moderate", "description": "RAIN is a powerful four-step process for working with difficult emotions developed by meditation teacher Tara Brach. Instead of suppressing or being overwhelmed by challenging feelings, you learn to meet them with mindful awareness and self-compassion. This practice transforms your relationship with difficult emotions, building emotional resilience and self-acceptance.", "instructions": "When a difficult emotion arises, pause. Recognize: Name what you're feeling. Allow: Let the emotion be present without trying to fix or change it. Investigate: With kindness, explore where you feel it in your body and what it needs. Nurture: Offer yourself compassion - place a hand on your heart and speak kindly to yourself as you would to a dear friend.", "benefits": "Processes difficult emotions skillfully, builds emotional intelligence, increases self-compassion, reduces emotional reactivity"},
    {"id": "mind_7", "title": "Mindful Listening", "duration_minutes": 10, "difficulty": "easy", "description": "This practice trains your attention by using sounds as anchors for awareness, teaching you to observe without labeling or judging. By noticing sounds arise and fade without getting caught in stories about them, you develop the skill of non-reactive awareness. This translates to better listening in conversations and reduced reactivity to life's challenges.", "instructions": "Sit comfortably and close your eyes. Instead of focusing on breath, make sounds your meditation object. Notice sounds near you and far away. Don't label them as 'car' or 'bird' - just hear them as pure sound. Notice the silence between sounds. When thoughts arise, gently return to listening. Let sounds come and go like waves.", "benefits": "Develops concentration and presence, reduces mental chatter, improves listening skills, cultivates non-reactive awareness"},
    {"id": "mind_8", "title": "Thought Labeling", "duration_minutes": 15, "difficulty": "moderate", "description": "This metacognitive practice helps you recognize that thoughts are temporary mental events, not facts or commands you must obey. By gently labeling thoughts as they arise, you create psychological distance from them, reducing their power over you. This is particularly effective for breaking cycles of rumination, worry, and negative self-talk.", "instructions": "Sit in meditation posture and close your eyes. As thoughts arise, mentally note their category: 'planning', 'worrying', 'remembering', 'judging', or simply 'thinking'. Don't engage with the content - just label and let go. Imagine thoughts as clouds passing through the sky of your awareness. Return to your breath between thoughts. Practice for 15 minutes.", "benefits": "Creates psychological distance from thoughts, reduces rumination and worry, improves metacognition, breaks negative thought patterns"},
    {"id": "mind_9", "title": "Gratitude Reflection", "duration_minutes": 10, "difficulty": "easy", "description": "Mindfully reflect on things you're grateful for.", "instructions": "Think of 3 things you're grateful for. Really feel the gratitude. Notice sensations in body.", "benefits": "Increases positive emotions, improves mood"},
    {"id": "mind_10", "title": "Mountain Meditation", "duration_minutes": 15, "difficulty": "moderate", "description": "Embody stability and strength of a mountain.", "instructions": "Sit with dignified posture. Visualize yourself as mountain. Weather passes, mountain remains unchanged.", "benefits": "Builds inner stability, develops equanimity"},
    {"id": "mind_11", "title": "Mindful Stretching", "duration_minutes": 10, "difficulty": "easy", "description": "Gentle stretches with full awareness.", "instructions": "Slowly stretch arms, neck, shoulders, back. Notice sensations. Breathe into stretch. Honor body's limits.", "benefits": "Releases physical tension, improves body awareness"},
    {"id": "mind_12", "title": "Noting Practice", "duration_minutes": 20, "difficulty": "moderate", "description": "Mental noting of present moment experience.", "instructions": "Notice predominant experience. Mentally note: 'hearing', 'feeling', 'thinking'. Brief notes only.", "benefits": "Develops clear seeing, reduces identification with experience"},
    {"id": "mind_13", "title": "3-Minute Breathing Space", "duration_minutes": 3, "difficulty": "easy", "description": "Quick centering practice.", "instructions": "Min 1: Acknowledge present. Min 2: Focus on breath. Min 3: Expand awareness to body and surroundings.", "benefits": "Quick reset, accessible anywhere, reduces stress rapidly"},
    {"id": "mind_14", "title": "Choiceless Awareness", "duration_minutes": 20, "difficulty": "challenging", "description": "Open monitoring of all experience.", "instructions": "Let awareness be open. Don't focus on anything specific. Notice whatever arises without judgment.", "benefits": "Develops non-reactive awareness, deepens insight"},
    {"id": "mind_15", "title": "Mindful Hand Washing", "duration_minutes": 5, "difficulty": "easy", "description": "Transform routine into mindfulness practice.", "instructions": "Feel water temperature, smell soap, notice lather texture, feel rinsing, dry with full attention.", "benefits": "Brings mindfulness to daily life, builds habit"}
]

MEDITATION_EXERCISES = [
    {"id": "med_1", "title": "Breath Awareness Meditation", "duration_minutes": 10, "difficulty": "easy", "description": "Foundation practice focusing on natural breath.", "instructions": "Sit comfortably. Breathe naturally. Notice breath at nostrils or belly. When mind wanders, gently return.", "benefits": "Develops concentration, calms mind, foundation for all meditation"},
    {"id": "med_2", "title": "Mantra Meditation", "duration_minutes": 20, "difficulty": "easy", "description": "Repeat sacred word to focus mind.", "instructions": "Choose mantra (Om, Peace, So Hum). Repeat silently. When mind wanders, return to mantra.", "benefits": "Quiets mental chatter, induces relaxation response"},
    {"id": "med_3", "title": "Visualization Meditation", "duration_minutes": 15, "difficulty": "moderate", "description": "Create peaceful mental imagery.", "instructions": "Visualize peaceful place. Engage all senses. Notice colors, sounds, smells. Feel peace and safety.", "benefits": "Reduces stress, improves mood, enhances creativity"},
    {"id": "med_4", "title": "Zen Meditation (Zazen)", "duration_minutes": 25, "difficulty": "challenging", "description": "Sitting meditation with focus on posture.", "instructions": "Sit on cushion, legs crossed. Eyes half-open. Breathe naturally. Count breaths or just sit.", "benefits": "Develops discipline, deepens awareness, cultivates presence"},
    {"id": "med_5", "title": "Progressive Muscle Relaxation", "duration_minutes": 20, "difficulty": "easy", "description": "Systematically tense and release muscles.", "instructions": "Lie down. Tense feet for 5 seconds, release. Move up through all muscle groups to face.", "benefits": "Releases physical tension, reduces anxiety, improves sleep"},
    {"id": "med_6", "title": "Open Awareness Meditation", "duration_minutes": 20, "difficulty": "challenging", "description": "Rest in spacious awareness without object.", "instructions": "Sit comfortably. Let go of all techniques. Rest in natural awareness. Don't focus on anything.", "benefits": "Deepest form of meditation, cultivates non-dual awareness"},
    {"id": "med_7", "title": "Chakra Meditation", "duration_minutes": 30, "difficulty": "moderate", "description": "Focus on energy centers along spine.", "instructions": "Start at root chakra (red). Move up through all 7 chakras. Spend 3-5 minutes on each.", "benefits": "Balances energy, promotes spiritual growth, holistic wellness"},
    {"id": "med_8", "title": "Sound Bath Meditation", "duration_minutes": 20, "difficulty": "easy", "description": "Meditate with singing bowls or healing sounds.", "instructions": "Lie down. Play singing bowl or healing music. Let sound wash over you. Feel vibrations in body.", "benefits": "Deep relaxation, reduces stress, balances nervous system"},
    {"id": "med_9", "title": "Candle Gazing", "duration_minutes": 15, "difficulty": "moderate", "description": "Focus on candle flame to develop concentration.", "instructions": "Gaze at flame without blinking. When eyes water, close and visualize flame at third eye. Repeat.", "benefits": "Improves concentration, cleanses eyes, develops focus"},
    {"id": "med_10", "title": "Walking Meditation", "duration_minutes": 20, "difficulty": "easy", "description": "Formal walking practice with slow steps.", "instructions": "Walk very slowly. Notice lifting, moving, placing of each foot. Turn mindfully. Continue 20 minutes.", "benefits": "Combines movement with meditation, develops mindfulness"},
    {"id": "med_11", "title": "Yoga Nidra", "duration_minutes": 30, "difficulty": "easy", "description": "Yogic sleep - deep relaxation while aware.", "instructions": "Lie down. Set intention. Rotate awareness through body. Breathe awareness. Visualizations.", "benefits": "Profound relaxation, reduces insomnia, restores nervous system"},
    {"id": "med_12", "title": "Mindfulness of Emotions", "duration_minutes": 15, "difficulty": "moderate", "description": "Observe emotions without attachment.", "instructions": "Notice current emotional state. Where in body? What quality? Observe without judgment. Let it be.", "benefits": "Emotional regulation, reduces reactivity, builds emotional intelligence"},
    {"id": "med_13", "title": "Transcendental Meditation", "duration_minutes": 20, "difficulty": "easy", "description": "Effortless technique using mantra.", "instructions": "Think your mantra effortlessly. Don't concentrate. Let mantra come naturally. Practice twice daily.", "benefits": "Reduces stress, lowers blood pressure, improves cardiovascular health"},
    {"id": "med_14", "title": "Metta Meditation (Extended)", "duration_minutes": 30, "difficulty": "moderate", "description": "Extended loving-kindness for all beings.", "instructions": "Start with self. Extend to loved ones, neutral people, difficult people, all beings. Feel universal love.", "benefits": "Increases compassion, reduces negative emotions, improves relationships"},
    {"id": "med_15", "title": "Silent Sitting", "duration_minutes": 45, "difficulty": "challenging", "description": "Extended silent meditation without technique.", "instructions": "Sit in stable posture. No technique, just sit. Be with whatever arises. Don't move unless necessary.", "benefits": "Develops deep concentration, builds resilience, profound insight"}
]

def get_exercises_by_time(category: str, available_minutes: int, max_results: int = 5) -> List[Dict[str, Any]]:
    """Get exercises filtered by available time"""
    if category == "breathing":
        exercises = BREATHING_EXERCISES
    elif category == "mindfulness":
        exercises = MINDFULNESS_EXERCISES
    elif category == "meditation":
        exercises = MEDITATION_EXERCISES
    else:
        return []
    
    # Filter by time (exercises that fit within available time)
    filtered = [ex for ex in exercises if ex["duration_minutes"] <= available_minutes]
    
    # Sort by duration (closest to available time first)
    filtered.sort(key=lambda x: abs(x["duration_minutes"] - available_minutes))
    
    return filtered[:max_results]
