#!/usr/bin/env python3
"""
Convert Water Quest chapters 5-30 to one-at-a-time interactive pattern
"""

# Chapter 5-30 interactive implementations
chapters_code = {
    5: """
// Chapter 5: Stealth Investigation
function loadStealthGame(c){c.innerHTML='<div class="mini-game-container"><h4>Stealth Investigation</h4><div class="learning-box" style="background:#e3f2fd;padding:15px;border-radius:8px;margin:15px 0"><h4 style="margin-top:0">Learning Goal: Industrial Pollution and Environmental Laws</h4><p><strong>Illegal discharge:</strong> Factories must treat wastewater before releasing it. Dumping untreated chemicals is illegal.</p><p><strong>Why evidence matters:</strong> Photos and water samples prove violations. Without proof polluters deny responsibility.</p></div><p><strong>Instructions:</strong> Choose ONE approach at a time to gather evidence!</p><div id="approachList"></div><div class="sample-grid" id="approachGrid"></div><div id="approachFeedback"></div></div>';renderApproachGrid()}
let approachesTried=[];let evidenceGathered=false;
function renderApproachGrid(){const approaches=[{id:'front',icon:'🚪',name:'Front Gate',success:false},{id:'side',icon:'🌳',name:'Side Fence',success:true},{id:'night',icon:'⏰',name:'Wait for Night',success:true}];let html='';approaches.forEach(a=>{const tried=approachesTried.includes(a.id);const disabled=tried?'opacity:0.5;pointer-events:none;':'';html+=`<div class="sample-card" style="${disabled}" onclick="tryApproach('${a.id}')"><div class="icon">${a.icon}</div><div class="label">${a.name}</div>${tried?'<div style="font-size:10px;color:#28a745">Tried</div>':''}</div>`});document.getElementById('approachGrid').innerHTML=html;updateApproachList()}
function updateApproachList(){if(approachesTried.length===0)return;let html='<div class="learning-box" style="background:#f0f0f0;padding:10px;margin:10px 0"><strong>Approaches Tried:</strong> '+approachesTried.length+'/3';if(evidenceGathered){html+=' | <span style="color:#28a745">Evidence gathered!</span>'}html+='</div>';document.getElementById('approachList').innerHTML=html}
function tryApproach(id){if(approachesTried.includes(id))return;approachesTried.push(id);const data={front:{success:false,education:'<strong>Front Gate - DETECTED!</strong><br><br>Result: Security spotted you immediately<br><br>What happened: The front gate has cameras and guards. This direct approach is too risky for undercover investigation.<br><br>Lesson: Sometimes the obvious path is not the best. Environmental investigators must be strategic and patient.'},side:{success:true,education:'<strong>Side Fence - SUCCESS!</strong><br><br>Result: You collected photo evidence and water samples undetected<br><br>Evidence gathered:<br>- Photos of illegal discharge pipe<br>- Water samples showing high toxicity<br>- Documentation of violations<br><br>Why this worked: Side entrance had less security. Patient observation found the gap.<br><br>Legal power: This evidence can force the factory to stop polluting under the Clean Water Act!'},night:{success:true,education:'<strong>Wait for Night - SUCCESS!</strong><br><br>Result: Night shift has minimal security. You gathered comprehensive evidence<br><br>Evidence gathered:<br>- Photos of illegal nighttime dumping<br>- Water samples during discharge<br>- Timestamp documentation<br><br>Why this worked: Patience pays off. Many illegal activities happen at night when fewer people are watching.<br><br>Bonus: Night photos prove intentional violation not accidental spill!'}};const result=data[id];let html='<div class="data-chart" style="margin:20px 0;padding:20px;background:'+(result.success?'#d4edda':'#ffebee')+';border-radius:8px;border-left:4px solid '+(result.success?'#28a745':'#e74c3c')+'"><div style="font-size:14px;line-height:1.6">'+result.education+'</div></div>';if(result.success){html+='<div class="learning-box" style="background:#d4edda;padding:15px;margin:15px 0;border-radius:8px;border-left:4px solid #28a745"><h4 style="margin-top:0">Evidence Collected!</h4><p>You can now report this to authorities!</p></div>';evidenceGathered=true;gameState.ecoPoints+=100;gameState.dataCollected+=2;updateStats();html+='<button class="btn btn-success" onclick="completeChapter()" style="margin:10px 5px">Report to Authorities</button>';if(approachesTried.length<3){html+='<button class="btn btn-secondary" onclick="clearApproachFeedback()" style="margin:10px 5px">Try Another Approach</button>'}}else{gameState.trustLevel-=5;updateStats();html+='<button class="btn btn-primary" onclick="clearApproachFeedback()" style="margin:10px">Try Another Approach</button>'}document.getElementById('approachFeedback').innerHTML=html;renderApproachGrid()}
function clearApproachFeedback(){document.getElementById('approachFeedback').innerHTML='';renderApproachGrid()}
""",
    # Add more chapters here - for now showing the pattern
}

print("Chapter conversion templates created")
print("Chapters 5-30 need individual interactive implementations")
print("Pattern: Select one option at a time, get educational feedback, find best answer")
