[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT = "8000"
PYTHONPATH = "/app"

[[services]]
name = "backend"
source = "backend"

[services.healthcheck]
path = "/health"
timeout = 30
interval = 10

[services.variables]
PORT = "8000"
PYTHONPATH = "/app"
