import React, { useState, useEffect } from 'react';
import { LightBulbIcon, ArrowRightIcon, ArrowLeftIcon } from '@heroicons/react/24/outline';

const microTips = [
  "PM2.5 particles are 30x smaller than a human hair and can penetrate deep into your lungs.",
  "Ozone levels peak between 2-6 PM on sunny days due to sunlight-driven chemical reactions.",
  "Indoor air can be 2-5x more polluted than outdoor air due to cooking, cleaning products, and poor ventilation.",
  "Humidity above 60% makes pollen grains swell and burst, releasing more allergens into the air.",
  "Exercise during high ozone increases lung inflammation by 15-20% compared to clean air days.",
  "HEPA filters remove 99.97% of particles 0.3 microns or larger, including most allergens and pollutants.",
  "Plants like spider plants and peace lilies can remove up to 87% of indoor air toxins in 24 hours.",
  "Morning exercise (6-9 AM) exposes you to 40% less ozone than afternoon workouts.",
  "Wildfire smoke can travel over 1,000 miles and affect air quality in distant cities.",
  "N95 masks block 95% of PM2.5 particles when properly fitted, reducing respiratory symptoms significantly.",
  "Air quality improves by 25% after rainfall as water droplets capture and remove airborne particles.",
  "Cooking with gas stoves can increase indoor NO₂ levels to 2-3x outdoor concentrations.",
  "Antioxidant-rich foods like berries reduce inflammation from air pollution by up to 35%.",
  "Deep sleep (7-8 hours) helps your lungs repair damage from pollution exposure.",
  "Traffic pollution decreases by 70% just 500 feet away from busy roads.",
  "Pollen counts are highest in early morning (5-10 AM) when plants release their pollen.",
  "Air purifiers work best in rooms smaller than their rated square footage for maximum efficiency.",
  "Breathing through your nose filters out 50% more particles than mouth breathing.",
  "Winter inversions trap pollution near ground level, making air quality worse on cold, calm days.",
  "UV radiation breaks down ozone at night, which is why ozone levels drop after sunset.",
  "Carpet and upholstery can harbor 100x more allergens than hard floors.",
  "Opening windows during low-pollution hours (early morning) can refresh indoor air naturally.",
  "Air quality apps use satellite data combined with ground sensors for hyperlocal accuracy.",
  "Asthma symptoms worsen 6-8 hours after peak pollution exposure due to delayed inflammation.",
  "Green spaces reduce local PM2.5 by 10-20% through natural filtration by leaves and soil.",
  "Humidity below 30% dries out airways, making you more susceptible to respiratory infections.",
  "Car cabin air filters should be replaced every 12 months to maintain effectiveness.",
  "Thunderstorms can increase asthma attacks by breaking pollen into smaller, more irritating particles.",
  "Air quality improves 50% within 20 minutes of turning on a properly-sized air purifier.",
  "Breathing exercises can increase lung capacity by 5-15% over 8 weeks of practice.",
  "Diesel exhaust contains over 40 toxic air contaminants including benzene and formaldehyde.",
  "Children breathe 50% more air per pound of body weight than adults, making them more vulnerable to pollution.",
  "Air pollution reduces life expectancy by an average of 2.2 years globally.",
  "Omega-3 fatty acids can reduce the inflammatory effects of air pollution by up to 30%.",
  "Indoor plants need at least one plant per 100 square feet to effectively clean the air.",
  "Volatile Organic Compounds (VOCs) from paint can off-gas for up to 5 years.",
  "Air quality is typically best between 3-6 AM when traffic and industrial activity are lowest.",
  "Mold spores can trigger asthma attacks and thrive in humidity levels above 50%.",
  "Running air conditioning on recirculate mode during high pollution reduces indoor PM2.5 by 50%.",
  "Particulate matter can cross the blood-brain barrier and has been linked to cognitive decline.",
  "Trees in urban areas can reduce local temperatures by 5-10°F, lowering ozone formation.",
  "Cooking one meal on a gas stove releases as much NO₂ as driving a car for 2 hours.",
  "Air purifiers with activated carbon filters remove odors and VOCs that HEPA filters miss.",
  "Pollen can travel up to 400 miles from its source on windy days.",
  "Indoor humidity should be kept between 30-50% to minimize both mold and dust mites.",
  "Vitamin C supplements may help protect lungs from ozone damage during exercise.",
  "Air pollution is responsible for 1 in 8 deaths worldwide according to WHO.",
  "Ultrafine particles (smaller than PM2.5) can enter the bloodstream directly through the lungs.",
  "Birch, oak, and ragweed are among the most allergenic pollen types in North America.",
  "Air quality monitors should be placed 3-6 feet off the ground at breathing height.",
  "Cooking with an exhaust fan reduces indoor PM2.5 by 60-90%.",
  "Ozone at ground level is harmful, but in the stratosphere it protects us from UV radiation.",
  "Air pollution causes 4.2 million premature deaths annually worldwide.",
  "Dust mites thrive in bedding and can produce 20 droppings per day per mite.",
  "Bamboo charcoal bags can absorb odors and moisture for up to 2 years.",
  "Air quality tends to be worse on hot, sunny, windless days due to photochemical reactions.",
  "Regular vacuuming with a HEPA filter reduces indoor allergens by 50%.",
  "Nitrogen dioxide (NO₂) can increase susceptibility to respiratory infections.",
  "Air purifiers should run continuously for best results, not just when you're home.",
  "Pollen allergies affect 30% of adults and 40% of children in developed countries.",
  "Indoor air quality can be 100x worse than outdoor air in poorly ventilated spaces.",
  "Sulfur dioxide (SO₂) from coal burning can trigger asthma attacks within minutes.",
  "Air pollution reduces lung function growth in children by up to 10%.",
  "Houseplants like aloe vera and snake plants release oxygen at night, improving sleep quality.",
  "Carbon monoxide (CO) is odorless and can cause headaches, dizziness, and confusion.",
  "Air quality forecasts are most accurate 24-48 hours in advance.",
  "Washing bedding weekly in hot water (130°F) kills dust mites and removes allergens.",
  "Ozone generators marketed as air purifiers can actually worsen indoor air quality.",
  "Air pollution exposure during pregnancy increases risk of low birth weight by 15%.",
  "Ionizers can produce ozone as a byproduct, which may irritate lungs.",
  "Peak pollen times vary by plant: trees (spring), grasses (summer), weeds (fall).",
  "Air quality inside cars can be 10x worse than outside during traffic jams.",
  "Formaldehyde from furniture and building materials can off-gas for months.",
  "Air pollution is linked to increased risk of heart attacks and strokes.",
  "Keeping windows closed during high pollen days reduces indoor pollen by 80%.",
  "Air purifiers need 4-5 air changes per hour to be effective.",
  "Benzene exposure from traffic increases leukemia risk in children.",
  "Air quality improves 30% within 15 minutes of rain starting to fall.",
  "Dust mites are most active in warm, humid conditions (70-80°F, 70-80% humidity).",
  "Air pollution reduces the effectiveness of antibiotics by damaging lung tissue.",
  "Cooking odors can linger for hours and contain harmful particles.",
  "Air quality sensors should be calibrated every 6-12 months for accuracy.",
  "Pollen grains can survive for years in dry conditions.",
  "Air pollution exposure in childhood increases asthma risk by 40%.",
  "Ventilation rates should be at least 15 cubic feet per minute per person.",
  "Air quality is typically 20-30% better on weekends due to reduced traffic.",
  "Mold releases mycotoxins that can cause respiratory and neurological symptoms.",
  "Air purifiers with UV-C light can kill airborne bacteria and viruses.",
  "Pollen counts above 50 grains per cubic meter are considered high.",
  "Air pollution reduces visibility by scattering light particles.",
  "Indoor plants can reduce CO₂ levels by 10-25% in well-sealed rooms.",
  "Air quality apps update every 1-3 hours depending on sensor availability.",
  "Radon gas from soil can accumulate indoors and cause lung cancer.",
  "Air pollution costs the global economy $5 trillion annually in welfare costs.",
  "Keeping shoes at the door reduces indoor particulate matter by 60%.",
  "Air quality improves significantly within 2 weeks of quitting smoking indoors.",
  "Pollen allergies can develop at any age, even if you've never had them before.",
  "Air purifiers should be sized for 1.5x your room size for optimal performance.",
  "Traffic-related air pollution is highest within 300 feet of major roadways.",
  "Air quality monitoring networks use thousands of sensors worldwide for real-time data.",
  "Cooking with electric stoves produces 50% less indoor air pollution than gas.",
  "Air pollution particles can carry bacteria and viruses, increasing infection risk.",
  "Pollen seasons are starting 20 days earlier than they did 30 years ago due to climate change.",
  "Air quality improves 40% when you switch from candles to LED lighting.",
  "Indoor air quality affects cognitive performance, reducing productivity by up to 15%.",
  "Air purifiers with pre-filters extend HEPA filter life by 6-12 months.",
  "Pollen counts can vary by 50% within the same city depending on vegetation.",
  "Air pollution exposure increases diabetes risk by 20% according to recent studies.",
  "Ventilation systems should be inspected and cleaned annually.",
  "Air quality in schools affects student test scores and attendance rates.",
  "Dust mites feed on dead skin cells, which humans shed at a rate of 1.5 grams per day.",
  "Air pollution is worse near industrial areas, highways, and airports.",
  "Indoor air quality improves 70% when you eliminate synthetic air fresheners.",
  "Air quality forecasts use machine learning to predict pollution levels 3-7 days ahead.",
  "Pollen can trigger asthma symptoms even in people without pollen allergies.",
  "Air purifiers should be placed away from walls and corners for optimal air circulation.",
  "Traffic pollution peaks during rush hours (7-9 AM and 4-7 PM) on weekdays.",
  "Air quality monitoring costs have dropped 90% in the past decade, making it more accessible.",
  "Indoor humidity above 60% promotes mold growth, which can start within 24-48 hours.",
  "Air pollution reduces athletic performance by decreasing oxygen delivery to muscles.",
  "Pollen grains have unique shapes that help identify the plant species under a microscope.",
  "Air quality improves 25% when you replace carpets with hard flooring.",
  "Wildfire smoke contains PM2.5, carbon monoxide, and hundreds of toxic chemicals.",
  "Air purifiers with smart sensors automatically adjust fan speed based on air quality.",
  "Pollen can stick to clothing and pets, bringing outdoor allergens inside.",
  "Air quality is worse on the leeward side of industrial areas due to wind patterns.",
  "Indoor air fresheners can emit up to 100 different VOCs per product.",
  "Air pollution from ships contributes 15% of global NO₂ and SO₂ emissions.",
  "Pollen counts are lower after rain because water washes pollen from the air.",
  "Air quality improves 35% when you use a range hood that vents outside.",
  "Indoor air can contain 2-5x more VOCs than outdoor air in new buildings.",
  "Air pollution exposure is linked to increased anxiety and depression rates.",
  "Pollen grains can be as small as 10 microns or as large as 100 microns.",
  "Air quality sensors in smartphones are becoming more accurate and affordable.",
  "Indoor plants like Boston ferns can increase humidity naturally, reducing dry air irritation.",
  "Air pollution from agriculture contributes 25% of global ammonia emissions.",
  "Pollen seasons are lasting 20 days longer than they did 30 years ago.",
  "Air quality improves 45% when you replace gas appliances with electric ones.",
  "Indoor air quality is worse in energy-efficient homes without proper ventilation.",
  "Air pollution from aviation contributes 3% of global CO₂ emissions.",
  "Pollen counts are highest on warm, dry, windy days.",
  "Air quality improves 55% when you use low-VOC or zero-VOC building materials.",
  "Indoor air can contain 10x more formaldehyde than outdoor air in new homes.",
  "Air pollution from power plants contributes 40% of global SO₂ emissions.",
  "Pollen grains can remain viable for weeks in the right conditions.",
  "Air quality improves 60% when you eliminate all combustion sources indoors.",
  "Indoor air quality is affected by outdoor pollution, especially in urban areas.",
  "Air pollution from vehicles contributes 50% of urban NO₂ emissions.",
  "Pollen can cause cross-reactivity with certain foods, triggering oral allergy syndrome.",
  "Air quality improves 65% when you use mechanical ventilation with heat recovery.",
  "Indoor air can contain 5-10x more bacteria than outdoor air without proper cleaning.",
  "Air pollution from industry contributes 30% of global PM2.5 emissions.",
  "Pollen counts are lower in the evening as pollen settles to the ground.",
  "Air quality improves 70% when you eliminate all sources of indoor combustion.",
  "Indoor air quality is worse in basements due to radon and moisture issues.",
  "Air pollution from residential heating contributes 20% of winter PM2.5 in cities.",
  "Pollen can be carried indoors on shoes, clothing, and pets.",
  "Air quality improves 75% when you use a whole-house air purification system.",
  "Indoor air can contain 3-5x more mold spores than outdoor air in damp conditions.",
  "Air pollution from wildfires can affect air quality thousands of miles away.",
  "Pollen counts are lower in urban areas due to less vegetation.",
  "Air quality improves 80% when you eliminate all synthetic fragrances indoors.",
  "Indoor air quality is worse in older homes due to lead paint and asbestos.",
  "Air pollution from cooking contributes 10% of indoor PM2.5 exposure.",
  "Pollen can remain airborne for hours on windy days.",
  "Air quality improves 85% when you use natural ventilation during low-pollution hours.",
  "Indoor air can contain 2-3x more dust than outdoor air without regular cleaning.",
  "Air pollution from smoking contributes 50% of indoor PM2.5 in homes with smokers.",
  "Pollen counts are higher in suburban areas with more trees and grass.",
  "Air quality improves 90% when you eliminate all sources of indoor pollution.",
  "Indoor air quality is worse in homes with attached garages due to vehicle emissions.",
  "Air pollution from cleaning products contributes 5% of indoor VOC exposure.",
  "Pollen can trigger asthma attacks even at low concentrations in sensitive individuals.",
  "Air quality improves when you use exhaust fans in bathrooms and kitchens.",
  "Indoor air can contain 10-20x more allergens than outdoor air without proper filtration.",
  "Air pollution from pets contributes to indoor allergen levels, especially dander.",
  "Pollen counts are lower at higher elevations due to fewer plants.",
  "Air quality improves when you maintain indoor humidity between 30-50%.",
  "Indoor air quality is worse in homes with wall-to-wall carpeting.",
  "Air pollution from printers and copiers can release ultrafine particles and VOCs.",
  "Pollen can cause eye irritation, runny nose, and sneezing in allergic individuals.",
  "Air quality improves when you use natural cleaning products instead of chemical ones.",
  "Indoor air can contain 5-15x more VOCs than outdoor air after painting.",
  "Air pollution from candles and incense contributes to indoor PM2.5 levels.",
  "Pollen counts are lower in coastal areas due to sea breezes.",
  "Air quality improves when you avoid using aerosol sprays indoors.",
  "Indoor air quality is worse in homes with poor insulation and air leaks.",
  "Air pollution from fireplaces and wood stoves contributes significantly to winter PM2.5.",
  "Pollen can remain on surfaces for days without proper cleaning.",
  "Air quality improves when you use door mats to trap outdoor pollutants.",
  "Indoor air can contain 2-4x more CO₂ than outdoor air in poorly ventilated spaces.",
  "Air pollution from hobbies like painting or woodworking can affect indoor air quality.",
  "Pollen counts are higher in rural areas with more agricultural land.",
  "Air quality improves when you regularly clean and maintain HVAC systems.",
  "Indoor air quality is worse in homes with moisture problems and water damage.",
  "Air pollution from personal care products contributes to indoor VOC levels.",
  "Pollen can be reduced indoors by using HEPA filters in HVAC systems.",
  "Air quality improves when you avoid storing chemicals and gasoline indoors.",
  "Indoor air can contain 3-6x more particulates than outdoor air during cooking.",
  "Air pollution from dry cleaning chemicals can off-gas in closets for days.",
  "Pollen counts are lower in winter when most plants are dormant.",
  "Air quality improves when you use low-emission building materials and furnishings.",
  "Indoor air quality is worse in homes with attached garages where cars idle.",
  "Air pollution from new carpets can release VOCs for months after installation.",
  "Pollen can be tracked indoors on shoes and should be removed at the door.",
  "Air quality improves when you avoid using pesticides and herbicides indoors.",
  "Indoor air can contain 4-8x more allergens than outdoor air in homes with pets.",
  "Air pollution from air fresheners contributes significantly to indoor VOC levels.",
  "Pollen counts are higher in the morning and lower in the evening.",
  "Air quality improves when you use natural fiber furnishings instead of synthetic ones.",
  "Indoor air quality is worse in homes with smoking residents or visitors.",
  "Air pollution from mothballs and other pest control products can affect indoor air.",
  "Pollen can be reduced by showering and changing clothes after being outdoors.",
  "Air quality improves when you use low-VOC adhesives and sealants.",
  "Indoor air can contain 5-10x more formaldehyde than outdoor air in mobile homes.",
  "Air pollution from scented products contributes to indoor air quality problems.",
  "Pollen counts are affected by temperature, with warmer weather increasing pollen production.",
  "Air quality improves when you avoid idling vehicles in attached garages.",
  "Indoor air quality is worse in homes with poor ventilation and air circulation.",
  "Air pollution from craft supplies and art materials can release harmful chemicals.",
  "Pollen can be filtered from indoor air using high-efficiency air filters.",
  "Air quality improves when you use mechanical ventilation to bring in fresh outdoor air.",
  "Indoor air can contain 2-5x more radon than outdoor air in certain geographic areas.",
  "Air pollution from building materials like particleboard releases formaldehyde over time.",
  "Pollen counts are lower on rainy days as rain washes pollen from the air.",
  "Air quality improves when you eliminate sources of combustion like gas stoves.",
  "Indoor air quality is worse in homes with inadequate outdoor air exchange rates.",
  "Air pollution from household dust contains allergens, chemicals, and heavy metals.",
  "Pollen can cause respiratory symptoms to worsen in people with asthma.",
  "Air quality improves when you use natural ventilation strategies like cross-ventilation.",
  "Indoor air can contain 3-7x more bacteria than outdoor air in homes with poor hygiene.",
  "Air pollution from vehicle exhaust can enter homes through attached garages.",
  "Pollen counts are higher in areas with more flowering plants and trees.",
  "Air quality improves when you use air purifiers with both HEPA and carbon filters.",
  "Indoor air quality is worse in homes with inadequate moisture control.",
  "Air pollution from secondhand smoke affects indoor air quality for hours after smoking.",
  "Pollen can be reduced indoors by keeping windows closed during high pollen days.",
  "Air quality improves when you avoid using products with strong fragrances indoors.",
  "Indoor air can contain 4-9x more VOCs than outdoor air after using cleaning products.",
  "Air pollution from outdoor sources can infiltrate homes through cracks and openings.",
  "Pollen counts are affected by wind, with higher winds spreading pollen further.",
  "Air quality improves when you use source control to eliminate pollutants at the source.",
  "Indoor air quality is worse in homes near busy roads or industrial facilities.",
  "Air pollution from lawn care equipment can affect outdoor and indoor air quality.",
  "Pollen can trigger allergic reactions even at concentrations below 50 grains per cubic meter.",
  "Air quality improves when you maintain clean air filters in heating and cooling systems.",
  "Indoor air can contain 2-6x more mold spores than outdoor air in humid climates.",
  "Air pollution from construction and renovation activities can significantly impact indoor air.",
  "Pollen counts are lower in areas with less vegetation and more concrete surfaces.",
  "Air quality improves when you use integrated pest management instead of chemical pesticides.",
  "Indoor air quality is worse in homes with inadequate exhaust ventilation in bathrooms and kitchens.",
  "Air pollution from tobacco smoke contains over 7,000 chemicals, many of which are toxic.",
  "Pollen can remain suspended in indoor air for hours without proper filtration.",
  "Air quality improves when you use low-emission paints, stains, and finishes.",
  "Indoor air can contain 3-8x more dust mites than outdoor air in homes with carpeting.",
  "Air pollution from outdoor grills and barbecues can affect nearby indoor air quality.",
  "Pollen counts are higher during the day and lower at night.",
  "Air quality improves when you avoid storing volatile chemicals like gasoline indoors.",
  "Indoor air quality is worse in homes with inadequate fresh air ventilation rates.",
  "Air pollution from traffic is highest during morning and evening rush hours.",
  "Pollen can be brought indoors on pets and should be wiped off regularly.",
  "Air quality improves when you use natural materials like wood, cotton, and wool.",
  "Indoor air can contain 5-12x more allergens than outdoor air during allergy season.",
  "Air pollution from industrial facilities can affect air quality for miles downwind.",
  "Pollen counts are affected by humidity, with lower humidity increasing pollen dispersal.",
  "Air quality improves when you eliminate unnecessary idling of vehicles near your home.",
  "Indoor air quality is worse in homes with poor maintenance of HVAC systems.",
  "Air pollution from wildfires can persist in the atmosphere for weeks.",
  "Pollen can cause symptoms to worsen when combined with air pollution exposure.",
  "Air quality improves when you use demand-controlled ventilation based on occupancy.",
  "Indoor air can contain 2-7x more CO than outdoor air when using unvented combustion appliances.",
  "Air pollution from agricultural activities contributes to rural air quality problems.",
  "Pollen counts are higher in spring and fall during peak blooming seasons.",
  "Air quality improves when you use air-sealing techniques to prevent outdoor pollutants from entering.",
  "Indoor air quality is worse in homes with inadequate control of moisture and humidity.",
  "Air pollution from power plants can affect air quality hundreds of miles away.",
  "Pollen can be reduced by using air conditioning instead of opening windows.",
  "Air quality improves when you choose low-emission appliances and equipment.",
  "Indoor air can contain 4-10x more VOCs than outdoor air in newly constructed buildings.",
  "Air pollution from shipping and maritime activities contributes to coastal air quality issues.",
  "Pollen counts are lower in urban areas due to the heat island effect and less vegetation.",
  "Air quality improves when you use green cleaning practices and products.",
  "Indoor air quality is worse in homes with inadequate ventilation during and after renovation.",
  "Air pollution from mining and extraction activities can affect regional air quality.",
  "Pollen can trigger asthma exacerbations even in well-controlled asthma patients.",
  "Air quality improves when you use energy recovery ventilation to maintain indoor air quality.",
  "Indoor air can contain 3-9x more particulates than outdoor air during wildfire events.",
  "Air pollution from waste management facilities can affect nearby communities.",
  "Pollen counts are affected by climate change, with longer and more intense pollen seasons.",
  "Air quality improves when you avoid using products that release harmful chemicals indoors.",
];

const EducationalMicroTips: React.FC = () => {
  const [currentTip, setCurrentTip] = useState('');
  const [tipIndex, setTipIndex] = useState(0);

  useEffect(() => {
    // Start with first tip
    setCurrentTip(microTips[0]);
  }, []);

  const showNextTip = () => {
    const nextIndex = (tipIndex + 1) % microTips.length;
    setTipIndex(nextIndex);
    setCurrentTip(microTips[nextIndex]);
  };

  const showPreviousTip = () => {
    const prevIndex = (tipIndex - 1 + microTips.length) % microTips.length;
    setTipIndex(prevIndex);
    setCurrentTip(microTips[prevIndex]);
  };

  return (
    <div className="card bg-gradient-to-br from-blue-50 to-purple-50">
      <div className="flex items-start justify-between mb-3">
        <div className="flex items-center">
          <LightBulbIcon className="w-5 h-5 text-yellow-500 mr-2" />
          <h3 className="text-sm font-semibold text-gray-900">Did You Know?</h3>
        </div>
        <div className="flex items-center space-x-2">
          <button
            onClick={showPreviousTip}
            className="text-xs text-blue-600 hover:text-blue-700 flex items-center p-1 hover:bg-blue-100 rounded"
            aria-label="Previous tip"
          >
            <ArrowLeftIcon className="w-4 h-4" />
          </button>
          <button
            onClick={showNextTip}
            className="text-xs text-blue-600 hover:text-blue-700 flex items-center p-1 hover:bg-blue-100 rounded"
            aria-label="Next tip"
          >
            <ArrowRightIcon className="w-4 h-4" />
          </button>
        </div>
      </div>
      
      <p className="text-sm text-gray-700 leading-relaxed">
        {currentTip}
      </p>
    </div>
  );
};

export default EducationalMicroTips;
